server:
  port: 8010

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000

crm:
  base-url: http://localhost:8010

inventory:
  base-url: http://localhost:8083

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

producer:
  scheduler:
    fixed-delay-ms: 60000
